import type { LinkItem } from "../types";

export const seedLinks: LinkItem[] = [
  {
    id: "seed-1",
    type: "link",
    url: "https://openai.com/research",
    title: "OpenAI research updates",
    domain: "openai.com",
    category: "AI News",
    source: "Web",
    tags: ["llm", "research", "openai"],
    notes: "Track model and product research announcements.",
    favorite: true,
    status: "unread",
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
    updatedAt: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: "seed-2",
    type: "link",
    url: "https://github.com/openai/openai-cookbook",
    title: "OpenAI Cookbook examples",
    domain: "github.com",
    category: "Projects",
    source: "GitHub",
    tags: ["open-source", "examples", "api"],
    notes: "Useful implementation patterns for API, structured output, and tools.",
    favorite: true,
    status: "read",
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: "seed-3",
    type: "link",
    url: "https://arxiv.org/list/cs.AI/recent",
    title: "Recent AI papers on arXiv",
    domain: "arxiv.org",
    category: "Research",
    source: "Paper",
    tags: ["paper", "research", "to-read"],
    notes: "Check weekly for papers worth saving into focused tags.",
    favorite: false,
    status: "unread",
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: "seed-4",
    type: "link",
    url: "https://www.youtube.com/@AndrejKarpathy",
    title: "Andrej Karpathy YouTube",
    domain: "youtube.com",
    category: "YouTube",
    source: "YouTube",
    tags: ["youtube", "learning", "llm"],
    notes: "Long-form AI engineering explanations.",
    favorite: false,
    status: "read",
    createdAt: Date.now() - 1000 * 60 * 60 * 36,
    updatedAt: Date.now() - 1000 * 60 * 60 * 36,
  },
  {
    id: "seed-5",
    type: "link",
    url: "https://www.langchain.com/",
    title: "LangChain agent framework",
    domain: "langchain.com",
    category: "Agents",
    source: "Web",
    tags: ["agents", "framework", "tools"],
    notes: "Reference when comparing agent orchestration options.",
    favorite: false,
    status: "unread",
    createdAt: Date.now() - 1000 * 60 * 60 * 54,
    updatedAt: Date.now() - 1000 * 60 * 60 * 54,
  },
];
